--zad1--
alter TABLE PROJEKTY
add (CONSTRAINT PK_PROJEKTY PRIMARY KEY(ID_PROJEKTU),
    CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU),
    CHECK (DATA_ZAKONCZENIA > DATA_ROZPOCZECIA),
    CHECK (FUNDUSZ > 0 OR FUNDUSZ IS NULL)
    );

alter Table PROJEKTY
MODIFY OPIS_PROJEKTU Not null;

SELECT constraint_name, constraint_type, search_condition, column_name
FROM USER_CONSTRAINTS 
NATURAL JOIN USER_CONS_COLUMNS  
join user_tab_columns utc using(column_name)
where utc.table_name = 'PROJEKTY'
order by constraint_name;
--ZAD2
INSERT INTO PROJEKTY(OPIS_PROJEKTU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,FUNDUSZ)
VALUES('INDEKSY BITMAPOWE',DATE '2015-04-12',DATE '2016-09-30',40000);
--POLECENIE NIE POWIOD£O SIÊ, PONIEWA¯ DUPLIKACJA OPIS_PROJEKTU NARUSZA WIÊZY UNIKATOWE 
--zad3

create table przydzialy (
id_projektu NUMBER(4),
nr_pracownika NUMBER(6),
od DATE DEFAULT SYSDATE,
do Date,
stawka NUMBER(7,2),
rola VARCHAR2(20 CHAR),

CONSTRAINT  PK_PRZYDZIALY PRIMARY KEY(ID_PROJEKTU, NR_PRACOWNIKA),
constraint FK_PRZYDZIALY_01 FOREIGN KEY(ID_PROJEKTU) references PROJEKTY(ID_PROJEKTU),
constraint FK_PRZYDZIALY_02 FOREIGN KEY(nr_pracownika) references PRACOWNICY(ID_PRAC),
CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(DO>OD),
CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA>0),
CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJ¥CY','ANALITYK', 'PROGRAMISTA')));
--zad4--
insert into przydzialy
values((select id_projektu from PROJEKTY WHERE OPIS_PROJEKTU IN ('INDEKSY BITMAPOWE')), 170,date '1999-04-10',date '1999-05-10',1000,'KIERUJ¥CY');
insert into przydzialy
values((select id_projektu from PROJEKTY WHERE OPIS_PROJEKTU IN ('INDEKSY BITMAPOWE')), 140,date '2000-12-01',NULL,1500,'ANALITYK');
insert into przydzialy
values((select id_projektu from PROJEKTY WHERE OPIS_PROJEKTU IN ('SIECI KRÊGOS£UPOWE')), 140,date '2015-09-14',NULL,2500,'KIERUJ¥CY');

--zad5--
alter table PRZYDZIALY
add GODZINY NUMBER(4) NOT NULL; --NIE, NIE MO¯NA DODAÆ DO TABELI KOLUMNY Z ATRYBUTEM NOT NULL, GDY ISTNIEJ¥ JU¯ W NIEJ REKORDY
--zad6--
alter table PRZYDZIALY
add GODZINY NUMBER(4);
UPDATE przydzialy
SET GODZINY = 24;
alter table PRZYDZIALY
MODIFY GODZINY NOT NULL;
--ZAD7--
ALTER TABLE PROJEKTY
DISABLE CONSTRAINT UK_PROJEKTY;
SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME IN('UK_PROJEKTY');
--ZAD8--
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)

VALUES('INDEKSY BITMAPOWE', '2015-04-12', '2016-09-30', 40000);
--ZAD9--
ALTER TABLE PROJEKTY
ENABLE CONSTRAINT UK_PROJEKTY; --NIE MO¯NA W£¥CZYÆ OGRANICZENIA GDY WCZEŒNIEJ W TABELI NIE JEST ONO SPE£NIONE
--ZAD10--
SELECT * FROM PROJEKTY;

UPDATE PROJEKTY
SET OPIS_PROJEKTU = 'Inne indeksy'
WHERE FUNDUSZ = 40000;
ALTER TABLE PROJEKTY 
ENABLE CONSTRAINT UK_PROJEKTY;
ALTER TABLE PROJEKTY
MODIFY opis_projektu VARCHAR2(10 CHAR); -- nie mo¿na zmniejszyæ maksymalnej d³ugoœci znaków gdy conajmniej jeden rekord nie spe³nia tego warunku
DELETE FROM PROJEKTY
WHERE OPIS_PROJEKTU = 'SIECI KRÊGOS£UPOWE';